services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: docker-compose.yaml

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: docker-compose.yaml

networks:
  mern:

volumes:
  node_modules:
