services:

  backend:
    extends:
      service: backend
      file: packages/backend/docker-compose.yaml

  frontend:
    extends:
      service: frontend
      file: packages/frontend/docker-compose.yaml

volumes:
  node_modules:
    name: node-modules

networks:
  mern:
    name: mern
