services:
  backend:
    container_name: chat-backend
    image: chat-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    env_file: .env
    networks:
      - mern
    ports:
      - 5000:5000
    volumes:
      - .:/chat-backend
      - node_modules:/chat-backend/node_modules

volumes:
  node_modules:
    name: node-modules
